<div class="modal fade" id="projectWebModal" tabindex="-1" role="dialog" aria-labelledby="projectWebModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
        <div class="modal-content border-0 shadow-lg">
            <div class="modal-header web-project-modal-header">
                <div><h5 class="modal-title font-weight-bold" id="projectWebModalLabel">Configurar proyecto web</h5><small class="text-muted">Presentación comercial en la landing pública.</small></div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar"><span aria-hidden="true">&times;</span></button>
            </div>
            <form id="projectWebForm" enctype="multipart/form-data" novalidate>
                @csrf
                <input type="hidden" id="webProjectId">
                <div class="modal-body bg-light p-3 p-md-4">
                    <section class="web-form-section"><h6><i class="fas fa-building"></i> Proyecto</h6><div class="row"><div class="col-md-4"><span class="web-label">PROYECTO</span><strong id="webProjectName">—</strong></div><div class="col-md-4"><span class="web-label">EMPRESA</span><span id="webProjectCompany">—</span></div><div class="col-md-4"><span class="web-label">UBICACIÓN</span><span id="webProjectLocation">—</span></div></div></section>
                    <section class="web-form-section"><h6><i class="fas fa-bullhorn"></i> Publicación</h6><div class="form-row"><div class="form-group col-md-3"><label for="webShow">VISIBILIDAD</label><select class="form-control" id="webShow" name="show_on_web"><option value="0">No publicar</option><option value="1">Mostrar en web</option></select><div class="invalid-feedback" data-error="show_on_web"></div></div><div class="form-group col-md-3"><label for="webFeatured">PORTADA</label><select class="form-control" id="webFeatured" name="featured_on_home"><option value="0">Normal</option><option value="1">Destacado</option></select><div class="invalid-feedback" data-error="featured_on_home"></div></div><div class="form-group col-md-3"><label for="webStatus">ESTADO COMERCIAL</label><select class="form-control" id="webStatus" name="commercial_status">@foreach($statuses as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select><div class="invalid-feedback" data-error="commercial_status"></div></div><div class="form-group col-md-3"><label for="webOrder">ORDEN</label><input type="number" min="1" class="form-control" id="webOrder" name="sort_order" value="1"><div class="invalid-feedback" data-error="sort_order"></div></div></div></section>
                    <section class="web-form-section"><h6><i class="fas fa-images"></i> Imágenes</h6><div class="form-row">
                        @foreach([['cover','cover_image','PORTADA PRINCIPAL','Imagen horizontal requerida al publicar.'],['mobile','mobile_image','IMAGEN MÓVIL','Opcional; si se omite se usa la portada.']] as [$type,$name,$label,$help])
                        <div class="form-group col-md-6 web-upload" data-upload="{{ $type }}"><label>{{ $label }}</label><input type="file" id="web_{{ $name }}" name="{{ $name }}" accept=".jpg,.jpeg,.png,.webp"><label class="web-dropzone" for="web_{{ $name }}"><img data-preview hidden alt="Vista previa"><i class="fas fa-cloud-upload-alt"></i><strong>Seleccionar o arrastrar imagen</strong><small>{{ $help }} JPG, PNG o WEBP · máximo 5 MB.</small></label><div class="web-file-meta" data-file-meta hidden><span><strong data-file-name></strong><small data-file-size></small></span><button type="button" data-file-remove>Quitar nueva selección</button></div><div class="invalid-feedback" data-error="{{ $name }}"></div></div>
                        @endforeach
                    </div><div class="form-group mb-0"><label for="webImageAlt">TEXTO ALTERNATIVO</label><input class="form-control" id="webImageAlt" name="image_alt" maxlength="180"><div class="invalid-feedback" data-error="image_alt"></div></div></section>
                    <section class="web-form-section"><h6><i class="fas fa-map"></i> Plano y disponibilidad</h6><div class="form-row">
                        @foreach([['plan','plan_image','PLANO PRINCIPAL','JPG, PNG o WEBP · máximo 8 MB.'],['plan_mobile','plan_mobile_image','PLANO MÓVIL OPCIONAL','Si se omite se utilizará el plano principal.']] as [$type,$name,$label,$help])
                        <div class="form-group col-md-6 web-upload" data-upload="{{ $type }}"><label>{{ $label }}</label><input type="file" id="web_{{ $name }}" name="{{ $name }}" accept=".jpg,.jpeg,.png,.webp"><label class="web-dropzone web-plan-dropzone" for="web_{{ $name }}"><img data-preview hidden alt="Vista previa"><i class="fas fa-map-marked-alt"></i><strong>Seleccionar o arrastrar plano</strong><small>{{ $help }}</small></label><div class="web-file-meta" data-file-meta hidden><span><strong data-file-name></strong><small data-file-size></small></span><button type="button" data-file-remove>Quitar nueva selección</button></div><div class="invalid-feedback" data-error="{{ $name }}"></div></div>
                        @endforeach
                    </div><div class="form-row"><div class="form-group col-md-6 mb-md-0"><label for="webPlanImageAlt">TEXTO ALTERNATIVO DEL PLANO</label><input class="form-control" id="webPlanImageAlt" name="plan_image_alt" maxlength="180"><div class="invalid-feedback" data-error="plan_image_alt"></div></div><div class="form-group col-md-6 mb-0"><label for="webPlanCaption">TEXTO DEL PLANO</label><input class="form-control" id="webPlanCaption" name="plan_caption" maxlength="180" placeholder="Plano general del proyecto"><div class="invalid-feedback" data-error="plan_caption"></div></div></div></section>
                    <section class="web-form-section"><h6><i class="fas fa-align-left"></i> Contenido</h6><div class="form-group"><label for="webDescription">DESCRIPCIÓN BREVE</label><textarea class="form-control" id="webDescription" name="short_description" rows="3" maxlength="500"></textarea><div class="invalid-feedback" data-error="short_description"></div></div><div class="form-group mb-0"><label for="webBadge">ETIQUETA DESTACADA</label><input class="form-control" id="webBadge" name="badge_text" maxlength="80" placeholder="Ej. Nueva etapa"><div class="invalid-feedback" data-error="badge_text"></div></div></section>
                    <section class="web-form-section mb-0"><h6><i class="fas fa-eye"></i> Previsualización</h6><article class="web-card-preview"><div class="web-card-preview-image"><img id="webCardPreviewImage" hidden alt=""><span id="webCardPreviewBadge">PRÓXIMAMENTE</span></div><div class="web-card-preview-body"><small id="webCardPreviewCompany">Empresa</small><h4 id="webCardPreviewName">Proyecto</h4><p id="webCardPreviewDescription">Descripción comercial del proyecto.</p><strong id="webCardPreviewStatus">PRÓXIMAMENTE</strong></div></article></section>
                </div>
                <div class="modal-footer"><button type="button" class="btn btn-light border" data-dismiss="modal">Cancelar</button><button type="submit" class="btn btn-krea" id="saveProjectWeb"><i class="fas fa-save mr-1"></i><span>Guardar cambios</span></button></div>
            </form>
        </div>
    </div>
</div>
